### ISSUE TITLE
aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj14dkZaam81UGdHMA==

### ISSUE THREAD

**Issue by master7720** [pinkcig/pinkcig#1]
aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj14dkZaam81UGdHMA==

**Comment by master7720** [comment]
https://cdn.discordapp.com/attachments/872372889314279485/922834346086387782/image0.jpg

**Comment by master7720** [comment]
decode this^^^^

**Comment by pinkcig** [comment]
oh my god i hate you
